project(
  'armex',
  'c',
  version: '1.0'
)

# Build executable
executable(
  'helloworld',
  'helloworld.S',
  install: false,
  link_args: ['-nostartfiles', '-nodefaultlibs', '-nostdlib']
)

executable(
  'helloargs',
  'helloargs.S',
  install: false,
  link_args: ['-nostartfiles', '-nodefaultlibs', '-nostdlib']
)
